spring:
  datasource:
    url: jdbc:mysql://192.168.1.200:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&allowMultiQueries=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.212
    port: 7000
  session:
    timeout: 6000
mybatis:
  type-aliases-package: com.stream.order.entity
logging:
  path: /user/local/log
  level:
    com.stream.springboot.web.streamspringbootweb: DEBUG
    org.springframework.web: INFO
    org.hibernat: ERROR
server:
  port: 8080

